npm_publish:
  image: node:lts
  tags:
    - docker
    - npm
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish --access public --otp "$(curl -s $OTP_URL)"
  only:
    - tags
